// ...bovenkant blijft hetzelfde (functies/gebruikersinstructie)...
// Wijzig alleen de router.push in de button, gebruik correcte context (binnen component en hooks)...

import { useRouter } from 'next/navigation';
// ...rest component...
export default function DesignPageClient() {
  // ...code...
  const router = useRouter();
  // ...code...
  return (
    // ...code...
    <button
      className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium"
      onClick={() => router.push('/dashboard/ontwerp')}
    >
      Terug naar dashboard
    </button>
    // ...rest van de JSX...
  );
}
// Zorg dat useRouter in de component geïnitieerd is zodat 'router' beschikbaar is.
